### PR TITLE
Minor: Switch Default VS Code Shell to Bash

### PR DESCRIPTION
**Pull request by RoboticMind**
* Previously VS Code was using `/bin/sh` instead of `/bin/bash`

* Alternatively we could change the `SHELL` environment variable of the container from `/bin/sh` to `/bin/bash` which would achieve the same effect

### CODE REVIEW

**Comment by nicholasphair** [comment]
Isn't it already [set in the dockerfile?][1]. Any idea why it is not being picked up?


[1]: https://github.com/nicholasphair/moralpain_config/blob/e3138abe044454ee9672d3efb3c85d67a7aaddf2/Dockerfile#L10

**Comment by RoboticMind** [comment]
Seem that does not appear to change the SHELL environmental variable that VS Code looks at
```
$ echo $SHELL
/bin/sh
```
I think that would need to be set with a 

```
ENV SHELL /bin/bash
```

**Review by nicholasphair — CHANGES_REQUESTED** [review]
Please make the appropriate changes in the docker.

**Comment by RoboticMind** [comment]
Will do that in a bit when I get back home to my computer

**Comment by RoboticMind** [comment]
Created a PR for that change in the docker repo https://github.com/nicholasphair/moralpain_config/pull/3

Closing this PR in place of that one

**Pull request closed without merging**
